// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flow/card-preview.tsx": () => import("../components/mockups/flow/card-preview.tsx"),
  "./components/mockups/flow/landing.tsx": () => import("../components/mockups/flow/landing.tsx"),
  "./components/mockups/flow/photo.tsx": () => import("../components/mockups/flow/photo.tsx"),
  "./components/mockups/flow/quiz-confidence.tsx": () => import("../components/mockups/flow/quiz-confidence.tsx"),
  "./components/mockups/flow/quiz-energy.tsx": () => import("../components/mockups/flow/quiz-energy.tsx"),
  "./components/mockups/flow/quiz-name.tsx": () => import("../components/mockups/flow/quiz-name.tsx"),
  "./components/mockups/flow/quiz-nation.tsx": () => import("../components/mockups/flow/quiz-nation.tsx"),
  "./components/mockups/flow/quiz-walkout.tsx": () => import("../components/mockups/flow/quiz-walkout.tsx"),
  "./components/mockups/flow/quiz-weapon-flaw.tsx": () => import("../components/mockups/flow/quiz-weapon-flaw.tsx"),
  "./components/mockups/flow/rarity-reveal.tsx": () => import("../components/mockups/flow/rarity-reveal.tsx"),
  "./components/mockups/flow/result.tsx": () => import("../components/mockups/flow/result.tsx"),
  "./components/mockups/flow/scanner.tsx": () => import("../components/mockups/flow/scanner.tsx")
};
